# Generated by Django 4.2.6 on 2023-10-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='in_active',
        ),
    ]
