# Generated by Django 4.2.6 on 2023-10-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_story_in_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
    ]
